<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="PIT0901" failures="0" tests="6" name="testTakeaLot.ExeptionDemo" time="0.010" errors="0" timestamp="2022-05-02T16:34:00 SAST" skipped="0">
  <testcase classname="testTakeaLot.ExeptionDemo" name="ArithmeticException_Demo" time="0.002"/>
  <system-out/>
  <testcase classname="testTakeaLot.ExeptionDemo" name="ArrayIndexOutOfBound_Demo" time="0.002"/>
  <system-out/>
  <testcase classname="testTakeaLot.ExeptionDemo" name="StringIndexOutOfBound_Demo" time="0.001"/>
  <system-out/>
  <testcase classname="testTakeaLot.ExeptionDemo" name="File_notFound_Demo" time="0.002"/>
  <system-out/>
  <testcase classname="testTakeaLot.ExeptionDemo" name="NullPointer_Demo" time="0.002"/>
  <system-out/>
  <testcase classname="testTakeaLot.ExeptionDemo" name="NumberFormat_Demo" time="0.001"/>
  <system-out/>
</testsuite> <!-- testTakeaLot.ExeptionDemo -->
